apiVersion: v1
kind: BuildConfig
metadata:
  name: "nationalparks-pipeline"
spec:
  source:
    contextDir: Nationalparks
    type: Git
    git:
      uri: "https://github.com/uzugic/advdev_homework_template"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       env:
         - name: GUID
           valueFrom: 
             configMapKeyRef:
               name: basic-config
               key: GUID
         - name: CLUSTER
           valueFrom: 
             configMapKeyRef:
               name: basic-config
               key: CLUSTER
